apiVersion: apps/v1
kind: Deployment
metadata:
  name: topz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topz
  template:
    metadata:
      labels:
        app: topz
    spec:
      shareProcessNamespace: true
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
        - name: topz
          image: brendanburns/topz:db0fa58
          ports:
            - containerPort: 8080
          command:
            - /server
          args:
            - -addr
            - 0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: topz
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: topz
  labels:
    app: topz
spec:
  selector:
    app: topz
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: topz
