---
apiVersion: v1
kind: Pod
metadata:
  name: adapter-example
  namespace: default
  labels:
    app: exporter
spec:
  containers:
    - name: redis
      image: redis
    - name: exporter
      image: oliver006/redis_exporter
      ports:
        - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: exporter
  labels:
    app: exporter
spec:
  selector:
    app: exporter
  type: NodePort
  ports:
    - port: 9121
      targetPort: 9121
